# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85eab2e2cecc15cc63001c1f1fc2c877ecd69838c260456adcc516ff521282179cb590b1b061851f6c1a0d8f06b43862d364c03451249dd2f5297d61f066c38b

test:
  secret_key_base: cc3a70eeda2449b4502c449f9f7046208445988c2f495bbe76159c8435b5a815a74606e9fa1bd58402b5bcd2c236458b58ba235fb6b1ce764ed90d0fbb148b35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
